### ISSUE TITLE
Custom dest folder

### ISSUE THREAD

**Issue by vi-cat** [SnowdogApps/wombat#15]
Hi, 

My application is based from `Create React App`, and as such, I need to create Wombat's DB file in either `public/` or something like `src/db`.

I am trying to override the default `dest` folder like so `"dest": "./utils/api/wombat.db.json",` in the `wombat.config.json` file but it appears that the configuration is never updated. Is this a bug? am I doing something wrong?

**Comment by Igloczek** [comment]
Wombat is serverless oriented, don't share any part with any React, Vue or in general front-end app, so I don't know how to answer the question about the path where the DB is stored, since it's a separate thing.

There is no `dest` option supported in `wombat.config.json`, DB is by default saved in the same where the CLI command was executed.
